#!/bin/bash
# git pre-commit tests
#
# Install this with (Cloud 9):
#
# ln -s ~/workspace/scripts/pre-commit ~/workspace/.git/hooks/

# only test the prospective commit
# from: https://codeinthehole.com/tips/tips-for-using-a-git-pre-commit-hook/
#STASH_NAME="pre-commit-$(date +%s)"
#git stash save -q --keep-index $STASH_NAME

./scripts/run_tests.sh

#RESULT=$?
#STASHES=$(git stash list)
#if [[ $STASHES == "$STASH_NAME" ]]; then
#  git stash pop -q
#fi